gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M0 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M0 -value Dense4Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M0 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M0 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M0 -value Dense4Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M0 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M0 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M0 -value Dense4Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M0 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M0 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M0 -value Dense4Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M0 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M0 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M0 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M0 -value Dense4Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M0 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M0 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M0 -value Dense4Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M0 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M0 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M0 -value Dense4Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M0 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M0 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M0 -value NoBrush
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M0 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M0 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M0 -value Dense4Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M0 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M1 -value cyan
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M1 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M1 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M1 -value cyan
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M1 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M1 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M1 -value cyan
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M1 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M1 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M1 -value cyan
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M1 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M1 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M1 -value cyan
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M1 -value cyan
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M1 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M1 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M1 -value cyan
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M1 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M1 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M1 -value cyan
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M1 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M1 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M1 -value cyan
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M1 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M1 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M1 -value cyan
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M1 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M1 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M2 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M2 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M2 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M2 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M2 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M2 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M2 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M2 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M2 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M2 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M2 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M2 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M2 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M2 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M2 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M2 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M2 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M2 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M2 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M2 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M2 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M2 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M2 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M2 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M2 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M2 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M2 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M2 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M3 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M3 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M3 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M3 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M3 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M3 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M3 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M3 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M3 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M3 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M3 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M3 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M3 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M3 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M3 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M3 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M3 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M3 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M3 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M3 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M3 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M3 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M3 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M3 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M3 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M3 -value red
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M3 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M3 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M4 -value green
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M4 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M4 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M4 -value green
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M4 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M4 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M4 -value green
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M4 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M4 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M4 -value green
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M4 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M4 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M4 -value green
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M4 -value green
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M4 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M4 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M4 -value green
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M4 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M4 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M4 -value green
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M4 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M4 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M4 -value green
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M4 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M4 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M4 -value green
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M4 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M4 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M5 -value #b400ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M5 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M5 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M5 -value #b400ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M5 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M5 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M5 -value #b400ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M5 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M5 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M5 -value #b400ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M5 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M5 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M5 -value #b400ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M5 -value #b400ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M5 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M5 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M5 -value #b400ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M5 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M5 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M5 -value #b400ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M5 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M5 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M5 -value #b400ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M5 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M5 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M5 -value #b400ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M5 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M5 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M6 -value #ffaf00
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M6 -value Dense5Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M6 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M6 -value #ffaf00
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M6 -value Dense5Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M6 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M6 -value #ffaf00
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M6 -value Dense5Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M6 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M6 -value #ffaf00
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M6 -value Dense5Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M6 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M6 -value #ffaf00
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M6 -value #ffaf00
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M6 -value Dense5Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M6 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M6 -value #ffaf00
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M6 -value Dense5Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M6 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M6 -value #ffaf00
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M6 -value Dense5Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M6 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M6 -value #ffaf00
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M6 -value Dense5Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M6 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M6 -value #ffaf00
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M6 -value Dense5Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M6 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M7 -value blue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M7 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M7 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M7 -value blue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M7 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M7 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M7 -value blue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M7 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M7 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M7 -value blue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M7 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M7 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M7 -value blue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M7 -value blue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M7 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M7 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M7 -value blue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M7 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M7 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M7 -value blue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M7 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M7 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M7 -value blue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M7 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M7 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M7 -value blue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M7 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M7 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M8 -value #b450ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M8 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M8 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M8 -value #b450ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M8 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M8 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M8 -value #b450ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M8 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M8 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M8 -value #b450ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M8 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M8 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M8 -value #b450ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M8 -value #b450ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M8 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M8 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M8 -value #b450ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M8 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M8 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M8 -value #b450ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M8 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M8 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M8 -value #b450ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M8 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M8 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M8 -value #b450ff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M8 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M8 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M9 -value white
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M9 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M9 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M9 -value white
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M9 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M9 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M9 -value white
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M9 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M9 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M9 -value white
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M9 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M9 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M9 -value white
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M9 -value white
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M9 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M9 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M9 -value white
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M9 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M9 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M9 -value white
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M9 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M9 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M9 -value white
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M9 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M9 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M9 -value white
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M9 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M9 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M10 -value #ffafff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M10 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M10 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M10 -value #ffafff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M10 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M10 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M10 -value #ffafff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M10 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M10 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M10 -value #ffafff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M10 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M10 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M10 -value #ffafff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M10 -value #ffafff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M10 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M10 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M10 -value #ffafff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M10 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M10 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M10 -value #ffafff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M10 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M10 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M10 -value #ffafff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M10 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M10 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M10 -value #ffafff
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M10 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M10 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M11 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M11 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M11 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M11 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M11 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M11 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M11 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M11 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M11 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M11 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M11 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M11 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M11 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M11 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M11 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M11 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M11 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M11 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M11 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M11 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M11 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M11 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M11 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M11 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M11 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M11 -value yellow
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M11 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M11 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M12 -value deeppink
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M12 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M12 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M12 -value deeppink
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M12 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M12 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M12 -value deeppink
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M12 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M12 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M12 -value deeppink
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M12 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M12 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M12 -value deeppink
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M12 -value deeppink
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M12 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M12 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M12 -value deeppink
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M12 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M12 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M12 -value deeppink
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M12 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M12 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M12 -value deeppink
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M12 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M12 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M12 -value deeppink
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M12 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M12 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M13 -value #ffffbe
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M13 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M13 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M13 -value #ffffbe
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M13 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M13 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M13 -value #ffffbe
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M13 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M13 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M13 -value #ffffbe
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M13 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M13 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M13 -value #ffffbe
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M13 -value #ffffbe
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M13 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M13 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M13 -value #ffffbe
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M13 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M13 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M13 -value #ffffbe
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M13 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M13 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M13 -value #ffffbe
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M13 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M13 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M13 -value #ffffbe
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M13 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M13 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M14 -value chocolate
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M14 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M14 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M14 -value chocolate
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M14 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M14 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M14 -value chocolate
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M14 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M14 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M14 -value chocolate
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M14 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M14 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M14 -value chocolate
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M14 -value chocolate
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M14 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M14 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M14 -value chocolate
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M14 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M14 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M14 -value chocolate
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M14 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M14 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M14 -value chocolate
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M14 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M14 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M14 -value chocolate
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M14 -value Dense6Pattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M14 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M15 -value lightgray
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M15 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M15 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M15 -value lightgray
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M15 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M15 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M15 -value lightgray
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M15 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M15 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M15 -value lightgray
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M15 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M15 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M15 -value lightgray
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M15 -value lightgray
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M15 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M15 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M15 -value lightgray
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M15 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M15 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M15 -value lightgray
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M15 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M15 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M15 -value lightgray
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M15 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M15 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M15 -value lightgray
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M15 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M15 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M16 -value green4
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M16 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M16 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M16 -value green4
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M16 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M16 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M16 -value green4
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M16 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M16 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M16 -value green4
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M16 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M16 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M16 -value green4
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M16 -value green4
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M16 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M16 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M16 -value green4
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M16 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M16 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M16 -value green4
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M16 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M16 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M16 -value green4
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M16 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M16 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M16 -value green4
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M16 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M16 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M17 -value plum
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M17 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M17 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M17 -value plum
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M17 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M17 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M17 -value plum
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M17 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M17 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M17 -value plum
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M17 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M17 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M17 -value plum
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M17 -value plum
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M17 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M17 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M17 -value plum
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M17 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M17 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M17 -value plum
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M17 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M17 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M17 -value plum
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M17 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M17 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M17 -value plum
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M17 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M17 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M18 -value lightskyblue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M18 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M18 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M18 -value lightskyblue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M18 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M18 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M18 -value lightskyblue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M18 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M18 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M18 -value lightskyblue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M18 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M18 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M18 -value lightskyblue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M18 -value lightskyblue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M18 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M18 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M18 -value lightskyblue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M18 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M18 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M18 -value lightskyblue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M18 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M18 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M18 -value lightskyblue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M18 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M18 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M18 -value lightskyblue
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M18 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M18 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M19 -value gold2
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M19 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M19 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorContactLayer_M19 -value gold2
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchContactLayer_M19 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleContactLayer_M19 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPortShapeLayer_M19 -value gold2
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPortShapeLayer_M19 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePortShapeLayer_M19 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinLayer_M19 -value gold2
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinLayer_M19 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinLayer_M19 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorWiringGridLayer_M19 -value gold2
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M19 -value gold2
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M19 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M19 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutingBlockageLayer_M19 -value gold2
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutingBlockageLayer_M19 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutingBlockageLayer_M19 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorPinBlockageLayer_M19 -value gold2
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchPinBlockageLayer_M19 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStylePinBlockageLayer_M19 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTopologyEdgeLayer_M19 -value gold2
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTopologyEdgeLayer_M19 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTopologyEdgeLayer_M19 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorMetalAreaLayer_M19 -value gold2
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchMetalAreaLayer_M19 -value CrossPattern
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleMetalAreaLayer_M19 -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorRoutedLayer_M0_iprobe -value white
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchRoutedLayer_M0_iprobe -value NoBrush
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleRoutedLayer_M0_iprobe -value SolidLine
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting colorTextObjectLayer_M0_iprobe -value white
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting hatchTextObjectLayer_M0_iprobe -value NoBrush
gui_set_setting -window [gui_get_current_window -types Layout -mru] -setting lineStyleTextObjectLayer_M0_iprobe -value SolidLine
