proc gen_dummy_liberty {netlist_file liberty_file module_name} {
  
  if { [regexp "\.v\.gz" $netlist_file] } {
      exec less $netlist_file > __tmp_netlist_file.v
      set netlist_file __tmp_netlist_file.v
  }
  
  set file_r [open $netlist_file r]
  set file_w [open $liberty_file w]
  set record "false"
  set port_count "0"
  set verilog_line ""
  array unset port_table
  set read_index 0
  set is_in_module false
  while {![eof $file_r]} {

    if { [expr $read_index%100000] == 0 } { puts "-I- Reading Line $read_index" }
    incr read_index 
    
    set line [gets $file_r]
    set line [regsub -all " +\\\\" $line " "]
    set line [regsub -all "," $line " "]    
    
    if { [regexp "^module $module_name \|^module $module_name\\\(" $line]   }   { set is_in_module true }
    if { $is_in_module && [regexp "^endmodule" $line] } { set is_in_module false }
    
    if { !$is_in_module } { continue }
    
    if {([regexp "^ +input " $line]) || ([regexp "^ +output " $line]) || ([regexp "^ +inout " $line])} {
      set record "true"
    }
    if { $record == "true" } {
      if {$verilog_line == ""} {
        set verilog_line $line
      } else {
        set verilog_line "$verilog_line $line"
      }
      if {[regexp {;} $line]} {
        
#puts "LINE: $verilog_line"        
        
        # Collect info in verilog file
        # puts $file_w $verilog_line
        set direction [lindex $verilog_line 0]
        if {[regexp {\[([0-9]+)\:([0-9]+)\]} [lindex $verilog_line 1] match upper_bit lower_bit]} {
          for {set i 2} {$i<[llength $verilog_line]} {incr i} {
            
            if { [lindex $verilog_line $i] == ";" } { continue }
            set port_table($port_count) "[regsub {,|;} [lindex $verilog_line $i] {}] $direction $upper_bit $lower_bit"
            
            puts "1: [lindex $verilog_line $i] :: $port_table($port_count)"            
            
            incr port_count
          }
        } else {
          for {set i 1} {$i<[llength $verilog_line]} {incr i} {

            if { [lindex $verilog_line $i] == ";" } { continue }          
            set port_table($port_count) "[regsub {,|;} [lindex $verilog_line $i] {}] $direction single_bit single_bit"
            
            puts "2: [lindex $verilog_line $i] :: $port_table($port_count)"            
            
            incr port_count
          }
        }


        # End collect info in verilog file
       
        set record "false"
        set verilog_line ""
      }
    }
  }
  
  puts $file_w "library \($module_name \)\{"
  puts $file_w "  delay_model : table_lookup;"
  puts $file_w "  date : \"No Date\" ;"
  puts $file_w "  revision : \"1.0\" ;"
  puts $file_w "  library_features(report_delay_calculation); "
  puts $file_w "  bus_naming_style : \"%s\[%d\]\" ;"
  puts $file_w "  comment : \"Generated By manual script\" ;"
  puts $file_w "  "
  puts $file_w "  /* unit attributes */"
  puts $file_w "  capacitive_load_unit ( 1.0000,pf);"
  puts $file_w "  current_unit : \"1mA\" ;"
  puts $file_w "  pulling_resistance_unit : \"1kohm\" ;"
  puts $file_w "  time_unit : \"1ns\" ;"
  puts $file_w "  voltage_unit : \"1V\" ;"
  puts $file_w "  leakage_power_unit : \"1nW\" ;"
  puts $file_w "  "
  puts $file_w "  /* threshold definitions */"
  puts $file_w "  input_threshold_pct_fall : 50.0000;"
  puts $file_w "  input_threshold_pct_rise : 50.0000;"
  puts $file_w "  output_threshold_pct_fall : 50.0000;"
  puts $file_w "  output_threshold_pct_rise : 50.0000;"
  puts $file_w "  slew_lower_threshold_pct_fall : 30.0000;"
  puts $file_w "  slew_lower_threshold_pct_rise : 30.0000;"
  puts $file_w "  slew_upper_threshold_pct_fall : 70.0000;"
  puts $file_w "  slew_upper_threshold_pct_rise : 70.0000;"
  puts $file_w "  slew_derate_from_library : 0.5000;"
  puts $file_w "  "
  puts $file_w "  /* operating conditions */"
  puts $file_w "  operating_conditions (ssgnp_0p675v_0c_cworst_CCworst_T ){"
  puts $file_w "    process :  1.0000;"
  puts $file_w "    temperature :  0.0000;"
  puts $file_w "    voltage :  0.6750;"
  puts $file_w "    tree_type :  \"balanced_tree\" ;"
  puts $file_w "  }"
  puts $file_w "  default_operating_conditions : \"ssgnp_0p675v_0c_cworst_CCworst_T\" ;"
  puts $file_w "  nom_process : 1.0000;"
  puts $file_w "  nom_temperature : 0.0000;"
  puts $file_w "  nom_voltage : 0.6750;"
  puts $file_w "  "
  puts $file_w "  /* default attributes */"
  puts $file_w "  default_fanout_load : 1.0000;"
  puts $file_w "  default_inout_pin_cap : 1.0000;"
  puts $file_w "  default_input_pin_cap : 1.0000;"
  puts $file_w "  default_output_pin_cap : 0.0000;"
  puts $file_w "  default_wire_load_area : 0.0000;"
  puts $file_w "  default_wire_load_capacitance : 0.0000;"
  puts $file_w "  default_wire_load_resistance : 3.7000;"
  puts $file_w "  k_process_cell_rise :  0.0000;"
  puts $file_w "  k_process_cell_fall :  0.0000;"
  puts $file_w "  k_volt_cell_rise :  0.0000;"
  puts $file_w "  k_volt_cell_fall :  0.0000;"
  puts $file_w "  k_temp_cell_rise :  0.0000;"
  puts $file_w "  k_temp_cell_fall :  0.0000;"
  puts $file_w "  k_process_rise_transition :  0.0000;"
  puts $file_w "  k_process_fall_transition :  0.0000;"
  puts $file_w "  k_volt_rise_transition :  0.0000;"
  puts $file_w "  k_volt_fall_transition :  0.0000;"
  puts $file_w "  k_temp_rise_transition :  0.0000;"
  puts $file_w "  k_temp_fall_transition :  0.0000;"
  puts $file_w "  "
  puts $file_w "  /* templates */"
  puts $file_w "  define( min_delay_arc , timing , boolean ) ;"
  puts $file_w "  "
  puts $file_w "  /* end of header section */"
  puts $file_w "  "
  puts $file_w "  cell ($module_name ) \{ "
  puts $file_w "    area :  0.0000;"
  puts $file_w "    dont_touch : true ;"
  puts $file_w "    dont_use : true ;"
  puts $file_w "    timing_model_type : extracted ;"
  puts $file_w "    is_macro_cell : true ;"
  puts $file_w "  "

  for {set i 0} {$i<$port_count} {incr i} {

    puts "-D- $port_table($i)"
    
    if {[lindex $port_table($i) 2] == "single_bit"} {
      puts $file_w "    pin ([lindex $port_table($i) 0]) \{"
      puts $file_w "      direction : [lindex $port_table($i) 1] ;"
      if { [lindex $port_table($i) 0] == "grid_clk" } {
      puts $file_w "      clock : true ;  "
      puts $file_w "      direction : input ; "
      puts $file_w "      capacitance :  0.0075; "
      puts $file_w "      max_transition :  0.0600; "
      puts $file_w "      related_ground_pin :   \"VSS\" ; "
      puts $file_w "      related_power_pin :   \"VDD\" ; "
      puts $file_w "      min_period :  0.4385; "
      puts $file_w "       "
      puts $file_w "      /* Start of min_clock_tree_path arc of pin grid_clk wrt pin grid_clk */ "
      puts $file_w "      timing() \{  "
      puts $file_w "        timing_type : min_clock_tree_path ; "
      puts $file_w "        timing_sense : positive_unate ; "
      puts $file_w "        cell_rise (lut_timing_3 )\{ "
      puts $file_w "           values(\ "
      puts $file_w "            \" 0.4144, 0.4174, 0.4203, 0.4245, 0.4339, 0.4394, 0.4525, 0.4723\"  \\ "
      puts $file_w "            ); "
      puts $file_w "          \} "
      puts $file_w "        cell_fall (lut_timing_3 )\{ "
      puts $file_w "           values(\ "
      puts $file_w "            \" 0.4926, 0.4953, 0.4975, 0.5001, 0.5044, 0.5064, 0.5078, 0.5034\"  \\ "
      puts $file_w "            ); "
      puts $file_w "          \} "
      puts $file_w "        ocv_sigma_cell_rise (lut_timing_3 )\{ "
      puts $file_w "          sigma_type : early ; "
      puts $file_w "           values(\ "
      puts $file_w "            \" 0.0044, 0.0044, 0.0044, 0.0044, 0.0046, 0.0049, 0.0060, 0.0093\"  \\ "
      puts $file_w "            ); "
      puts $file_w "          \} "
      puts $file_w "        ocv_sigma_cell_fall (lut_timing_3 )\{ "
      puts $file_w "          sigma_type : early ; "
      puts $file_w "           values(\ "
      puts $file_w "            \" 0.0049, 0.0049, 0.0049, 0.0049, 0.0051, 0.0053, 0.0062, 0.0090\"  \\ "
      puts $file_w "            ); "
      puts $file_w "          \} "
      puts $file_w "        ocv_sigma_cell_rise (lut_timing_3 )\{ "
      puts $file_w "          sigma_type : late ; "
      puts $file_w "           values(\ "
      puts $file_w "            \" 0.0047, 0.0047, 0.0047, 0.0047, 0.0048, 0.0050, 0.0063, 0.0097\"  \\ "
      puts $file_w "            ); "
      puts $file_w "          \} "
      puts $file_w "        ocv_sigma_cell_fall (lut_timing_3 )\{ "
      puts $file_w "          sigma_type : late ; "
      puts $file_w "           values(\ "
      puts $file_w "            \" 0.0052, 0.0052, 0.0052, 0.0052, 0.0053, 0.0054, 0.0065, 0.0093\"  \\ "
      puts $file_w "            ); "
      puts $file_w "          \} "
      puts $file_w "        \} /* End of min_clock_tree_path arc of pin grid_clk wrt pin grid_clk */ "
      puts $file_w "         "
      puts $file_w "        /* Start of max_clock_tree_path arc of pin grid_clk wrt pin grid_clk */ "
      puts $file_w "        timing() \{  "
      puts $file_w "          timing_type : max_clock_tree_path ; "
      puts $file_w "          timing_sense : positive_unate ; "
      puts $file_w "          cell_rise (lut_timing_4 )\{ "
      puts $file_w "             values(\ "
      puts $file_w "              \" 0.5324, 0.5355, 0.5383, 0.5426, 0.5486, 0.5539, 0.5705, 0.5904\"  \\ "
      puts $file_w "              ); "
      puts $file_w "            \} "
      puts $file_w "          cell_fall (lut_timing_4 )\{ "
      puts $file_w "             values(\ "
      puts $file_w "              \" 0.5247, 0.5275, 0.5295, 0.5321, 0.5355, 0.5373, 0.5397, 0.5353\"  \\ "
      puts $file_w "              ); "
      puts $file_w "            \} "
      puts $file_w "          ocv_sigma_cell_rise (lut_timing_4 )\{ "
      puts $file_w "            sigma_type : early ; "
      puts $file_w "             values(\ "
      puts $file_w "              \" 0.0044, 0.0044, 0.0044, 0.0044, 0.0046, 0.0049, 0.0060, 0.0093\"  \\ "
      puts $file_w "              ); "
      puts $file_w "            \} "
      puts $file_w "          ocv_sigma_cell_fall (lut_timing_4 )\{ "
      puts $file_w "            sigma_type : early ; "
      puts $file_w "             values(\ "
      puts $file_w "              \" 0.0049, 0.0049, 0.0049, 0.0049, 0.0051, 0.0053, 0.0062, 0.0090\"  \\ "
      puts $file_w "              ); "
      puts $file_w "            \} "
      puts $file_w "          ocv_sigma_cell_rise (lut_timing_4 )\{ "
      puts $file_w "            sigma_type : late ; "
      puts $file_w "             values(\ "
      puts $file_w "              \" 0.0047, 0.0047, 0.0047, 0.0047, 0.0048, 0.0050, 0.0063, 0.0097\"  \\ "
      puts $file_w "              ); "
      puts $file_w "            \} "
      puts $file_w "          ocv_sigma_cell_fall (lut_timing_4 )\{ "
      puts $file_w "            sigma_type : late ; "
      puts $file_w "             values(\ "
      puts $file_w "              \" 0.0052, 0.0052, 0.0052, 0.0052, 0.0053, 0.0054, 0.0065, 0.0093\"  \\ "
      puts $file_w "              ); "
      puts $file_w "            \} "
      puts $file_w "          \} /* End of max_clock_tree_path arc of pin grid_clk wrt pin grid_clk */ "
      puts $file_w "          min_pulse_width_low :  0.1413; "
      puts $file_w "          min_pulse_width_high :  0.1187; "

      } else {
      puts $file_w "      capacitance :  0.0000;"
      }
      puts $file_w "    \}"
      puts $file_w ""
    } else {
      set bus_type bus_[lindex $port_table($i) 2]_[lindex $port_table($i) 3]
      if {![info exists bus_declared($bus_type)]} {
        set bus_declared($bus_type) 1
        puts $file_w "    type ($bus_type) \{"
        puts $file_w "      base_type : array ;"
        puts $file_w "      data_type : bit ;"
        puts $file_w "      bit_width :  [expr [lindex $port_table($i) 2] + 1];"
        puts $file_w "      bit_from :  [lindex $port_table($i) 2];"
        puts $file_w "      bit_to :  [lindex $port_table($i) 3];"
        puts $file_w "      downto : true ;"
        puts $file_w "    \}"
        puts $file_w ""
      }
      puts $file_w "    bus ([lindex $port_table($i) 0]) \{"
      puts $file_w "      bus_type :  $bus_type ;"
      puts $file_w ""
      for {set j [lindex $port_table($i) 3]} {$j<=[lindex $port_table($i) 2]} {incr j 1} {
        puts $file_w "      pin ([lindex $port_table($i) 0]\[$j\] ) \{"
        puts $file_w "        direction : [lindex $port_table($i) 1] ;"
        puts $file_w "        capacitance :  0.0000;"
        puts $file_w "      \}"
        puts $file_w ""      
      }
      puts $file_w "    \}"
      puts $file_w ""
    }
  }

  puts $file_w "  \} /* End of Design */"
  puts $file_w "  "
  puts $file_w "\} /* End of Library */"

  close $file_r
  close $file_w
  
#  if { [file exists __tmp_netlist_file.v] } {
#      exec rm __tmp_netlist_file.v
#  }
  
}
return
set netlist_list "/services/bespace/users/ory/nextflow_pre_pn85/be_work/brcm5/grid_quadrant/v9_grid_pn85.3_20220411_1027_post_dft/inter/inputs/pn85.3_post_dft/netlists/nfi_mcu_top.v.gz
/services/bespace/users/ory/nextflow_pre_pn85/be_work/brcm5/grid_quadrant/v9_grid_pn85.3_20220411_1027_post_dft/inter/inputs/pn85.3_post_dft/netlists/grid_quad_west_filler_ecore_row_top.v.gz
/services/bespace/users/ory/nextflow_pre_pn85/be_work/brcm5/grid_quadrant/v9_grid_pn85.3_20220411_1027_post_dft/inter/inputs/pn85.3_post_dft/netlists/grid_quad_east_filler_row_top.v.gz
/services/bespace/users/ory/nextflow_pre_pn85/be_work/brcm5/grid_quadrant/v9_grid_pn85.3_20220411_1027_post_dft/inter/inputs/pn85.3_post_dft/netlists/grid_quad_east_filler_row_7_top.v.gz
/services/bespace/users/ory/nextflow_pre_pn85/be_work/brcm5/grid_quadrant/v9_grid_pn85.3_20220411_1027_post_dft/inter/inputs/pn85.3_post_dft/netlists/grid_quad_west_filler_row_top.v.gz
/services/bespace/users/ory/nextflow_pre_pn85/be_work/brcm5/grid_quadrant/v9_grid_pn85.3_20220411_1027_post_dft/inter/inputs/pn85.3_post_dft/netlists/grid_quad_south_filler_east_col_top.v.gz
/services/bespace/users/ory/nextflow_pre_pn85/be_work/brcm5/grid_quadrant/v9_grid_pn85.3_20220411_1027_post_dft/inter/inputs/pn85.3_post_dft/netlists/grid_quad_south_filler_col_top.v.gz
/services/bespace/users/ory/nextflow_pre_pn85/be_work/brcm5/grid_quadrant/v9_grid_pn85.3_20220411_1027_post_dft/inter/inputs/pn85.3_post_dft/netlists/grid_quad_south_filler_col_0_top.v.gz
/services/bespace/users/ory/nextflow_pre_pn85/be_work/brcm5/grid_quadrant/v9_grid_pn85.3_20220411_1027_post_dft/inter/inputs/pn85.3_post_dft/netlists/cbue_top.v.gz
/services/bespace/users/ory/nextflow_pre_pn85/be_work/brcm5/grid_quadrant/v9_grid_pn85.3_20220411_1027_post_dft/inter/inputs/pn85.3_post_dft/netlists/tcu_top.v.gz
/services/bespace/users/ory/nextflow_pre_pn85/be_work/brcm5/grid_quadrant/v9_grid_pn85.3_20220411_1027_post_dft/inter/inputs/pn85.3_post_dft/netlists/grid_quad_east_filler_row_0_top.v.gz
/services/bespace/users/ory/nextflow_pre_pn85/be_work/brcm5/grid_quadrant/v9_grid_pn85.3_20220411_1027_post_dft/inter/inputs/pn85.3_post_dft/netlists/grid_quad_east_filler_row_notch_top.v.gz
/services/bespace/users/ory/nextflow_pre_pn85/be_work/brcm5/grid_quadrant/v9_grid_pn85.3_20220411_1027_post_dft/inter/inputs/pn85.3_post_dft/netlists/grid_quad_north_filler_col_top.v.gz
/services/bespace/users/ory/nextflow_pre_pn85/be_work/brcm5/grid_quadrant/v9_grid_pn85.3_20220411_1027_post_dft/inter/inputs/pn85.3_post_dft/netlists/cbui_top.v.gz"

set lib_dir ../inter/inputs/dummy_libs/libs
echo "" > no_found_files.txt 
foreach file $netlist_list {
    set module_name [regsub "\\\.v.gz" [lindex [split $file "/"] end] ""]
    puts $module_name
    
    if { ![file exists $file] } { echo "$file\n" >> no_found_files.txt ; continue }
    
    gen_dummy_liberty $file $lib_dir/${module_name}.dummy.lib $module_name
#    if { [file exists $lib_dir/${module_name}.dummy.lib] } {
#    
#    }
}
