#
################################################################
##  Generated by:      create_blackbox_file script
##  Generated on:      Tue Feb  1 09:41:17 IST 2022
##  Design:            cbui_top
##  Size:              759.696 544.32
##  File Name:         scripts_local/create_blackboxes.tcl
##  User:              ory
################################################################
#
#
#set cell cbui_top
#set myx  759.696
#set myy  514.080
#set bc [get_db base_cells $cell]
#set lc [get_db $bc .lib_cells]
#if { [get_db $bc .lef_file_name] != "" } {
#    set x [expr [get_db $bc .bbox.ur.x] - [get_db $bc .bbox.ll.x]]
#    set y [expr [get_db $bc .bbox.ur.y] - [get_db $bc .bbox.ll.y]]
#    puts "-I- Cell: $cell. Using lef x and y: $x $y VS $myx $myy"
#    if { $x != $myx || $y != $myy } { exit }
#    
#} else {
#    puts "-I- Cell: $cell. Using my x and y: $myx $myy"
#    set x $myx 
#    set y $myy
#}
#if { $lc == "" } { puts "-I- Cell: Creating BBOX"
#create_blackbox -cell $cell -size $x $y  -core_spacing 0 0 0 0 \
#    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
#    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
#    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
#}
#
################################################################
##  Generated by:      create_blackbox_file script
##  Generated on:      Tue Feb  1 09:41:17 IST 2022
##  Design:            nfi_mcu_top
##  Size:              406.98 1108.80
##  File Name:         scripts_local/create_blackboxes.tcl
##  User:              ory
################################################################
#
#
#set cell nfi_mcu_top
#set myx  434.112
#set myy  1108.80
#set bc [get_db base_cells $cell]
#set lc [get_db $bc .lib_cells]
#if { [get_db $bc .lef_file_name] != "" } {
#    set x [expr [get_db $bc .bbox.ur.x] - [get_db $bc .bbox.ll.x]]
#    set y [expr [get_db $bc .bbox.ur.y] - [get_db $bc .bbox.ll.y]]
#    puts "-I- Cell: $cell. Using lef x and y: $x $y VS $myx $myy"
#    if { $x != $myx || $y != $myy } { exit }
#    
#} else {
#    puts "-I- Cell: $cell. Using my x and y: $myx $myy"
#    set x $myx 
#    set y $myy
#}
#if { $lc == "" } { puts "-I- Cell: Creating BBOX"
#create_blackbox -cell $cell -size $x $y -core_spacing 0 0 0 0 \
#    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
#    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
#    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
#}
#
################################################################
##  Generated by:      create_blackbox_file script
##  Generated on:      Tue Feb  1 09:41:17 IST 2022
##  Design:            cbue_top
##  Size:              759.696 544.32
##  File Name:         scripts_local/create_blackboxes.tcl
##  User:              ory
################################################################
#
#
#
#set cell cbue_top
#set myx  759.696
#set myy  594.720
#set bc [get_db base_cells $cell]
#set lc [get_db $bc .lib_cells]
#if { [get_db $bc .lef_file_name] != "" } {
#    set x [expr [get_db $bc .bbox.ur.x] - [get_db $bc .bbox.ll.x]]
#    set y [expr [get_db $bc .bbox.ur.y] - [get_db $bc .bbox.ll.y]]
#    puts "-I- Cell: $cell. Using lef x and y: $x $y VS $myx $myy"
#    if { $x != $myx || $y != $myy } { exit }
#    
#} else {
#    puts "-I- Cell: $cell. Using my x and y: $myx $myy"
#    set x $myx 
#    set y $myy
#}
#if { $lc == "" } { puts "-I- Cell: Creating BBOX"
#create_blackbox -cell $cell -size $x $y -core_spacing 0 0 0 0 \
#    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
#    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
#    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
#}    
#
################################################################
##  Generated by:      create_blackbox_file script
##  Generated on:      Tue Feb  1 09:41:17 IST 2022
##  Design:            tcu_top
##  Size:              759.696 1108.80
##  File Name:         scripts_local/create_blackboxes.tcl
##  User:              ory
################################################################
#
#
#set cell tcu_top
#set myx  759.696
#set myy  1108.80
#set bc [get_db base_cells $cell]
#set lc [get_db $bc .lib_cells]
#if { [get_db $bc .lef_file_name] != "" } {
#    set x [expr [get_db $bc .bbox.ur.x] - [get_db $bc .bbox.ll.x]]
#    set y [expr [get_db $bc .bbox.ur.y] - [get_db $bc .bbox.ll.y]]
#    puts "-I- Cell: $cell. Using lef x and y: $x $y VS $myx $myy"
#    if { $x != $myx || $y != $myy } { exit }
#    
#} else {
#    puts "-I- Cell: $cell. Using my x and y: $myx $myy"
#    set x $myx 
#    set y $myy
#}
#if { $lc == "" } { puts "-I- Cell: Creating BBOX"
#create_blackbox -cell $cell -size $x $y -core_spacing 0 0 0 0 \
#    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
#    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
#    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
#}

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Tue Feb  1 09:41:17 IST 2022
#  Design:            grid_quad_east_filler_row_top
#  Size:              162.792 1108.80
#  File Name:         scripts_local/create_blackboxes.tcl
#  User:              ory
###############################################################


set cell grid_quad_east_filler_row_top
set myx  162.792 
set myy  1108.80
set bc [get_db base_cells $cell]
set lc [get_db $bc .lib_cells]
if { [get_db $bc .lef_file_name] != "" } {
    set x [expr [get_db $bc .bbox.ur.x] - [get_db $bc .bbox.ll.x]]
    set y [expr [get_db $bc .bbox.ur.y] - [get_db $bc .bbox.ll.y]]
    puts "-I- Cell: $cell. Using lef x and y: $x $y VS $myx $myy"
    if { $x != $myx || $y != $myy } { exit }
    
} else {
    puts "-I- Cell: $cell. Using my x and y: $myx $myy"
    set x $myx 
    set y $myy
}
if { $lc == "" } { puts "-I- Cell: Creating BBOX"
create_blackbox -cell $cell -size $x $y  -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
}    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Tue Feb  1 09:41:18 IST 2022
#  Design:            grid_quad_west_filler_row_top
#  Size:              54.264 1108.80
#  File Name:         scripts_local/create_blackboxes.tcl
#  User:              ory
###############################################################


set cell grid_quad_west_filler_row_top
set myx  27.132
set myy  1108.80
set bc [get_db base_cells $cell]
set lc [get_db $bc .lib_cells]
if { [get_db $bc .lef_file_name] != "" } {
    set x [expr [get_db $bc .bbox.ur.x] - [get_db $bc .bbox.ll.x]]
    set y [expr [get_db $bc .bbox.ur.y] - [get_db $bc .bbox.ll.y]]
    puts "-I- Cell: $cell. Using lef x and y: $x $y VS $myx $myy"
    if { $x != $myx || $y != $myy } { exit }
    
} else {
    puts "-I- Cell: $cell. Using my x and y: $myx $myy"
    set x $myx 
    set y $myy
}
if { $lc == "" } { puts "-I- Cell: Creating BBOX"
create_blackbox -cell $cell -size $x $y -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
}    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Tue Feb  1 09:41:18 IST 2022
#  Design:            grid_quad_south_filler_row_top
#  Size:              1193.808 20.16
#  File Name:         scripts_local/create_blackboxes.tcl
#  User:              ory
###############################################################


set cell grid_quad_south_filler_col_top
set myx  1193.808 
set myy  141.12
set bc [get_db base_cells $cell]
set lc [get_db $bc .lib_cells]
if { [get_db $bc .lef_file_name] != "" } {
    set x [expr [get_db $bc .bbox.ur.x] - [get_db $bc .bbox.ll.x]]
    set y [expr [get_db $bc .bbox.ur.y] - [get_db $bc .bbox.ll.y]]
    puts "-I- Cell: $cell. Using lef x and y: $x $y VS $myx $myy"
    if { $x != $myx || $y != $myy } { exit }
    
} else {
    puts "-I- Cell: $cell. Using my x and y: $myx $myy"
    set x $myx 
    set y $myy
}
if { $lc == "" } { puts "-I- Cell: Creating BBOX"
create_blackbox -cell $cell -size $x $y -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
}    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Tue Feb  1 09:41:18 IST 2022
#  Design:            grid_quad_north_filler_row_top
#  Size:              1193.808 20.16
#  File Name:         scripts_local/create_blackboxes.tcl
#  User:              ory
###############################################################


set cell grid_quad_north_filler_col_top
set myx  1193.808 
set myy  40.32
set bc [get_db base_cells $cell]
set lc [get_db $bc .lib_cells]
if { [get_db $bc .lef_file_name] != "" } {
    set x [expr [get_db $bc .bbox.ur.x] - [get_db $bc .bbox.ll.x]]
    set y [expr [get_db $bc .bbox.ur.y] - [get_db $bc .bbox.ll.y]]
    puts "-I- Cell: $cell. Using lef x and y: $x $y VS $myx $myy"
    if { $x != $myx || $y != $myy } { exit }
    
} else {
    puts "-I- Cell: $cell. Using my x and y: $myx $myy"
    set x $myx 
    set y $myy
}
if { $lc == "" } { puts "-I- Cell: Creating BBOX"
create_blackbox -cell $cell -size $x $y -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
}    


###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Tue Feb  1 09:41:17 IST 2022
#  Design:            grid_tcu_cluster
#  Size:              759.696 1108.80
#  File Name:         scripts_local/create_blackboxes.tcl
#  User:              ory
###############################################################


set cell grid_tcu_cluster
set myx  1193.808
set myy  1108.80
set bc [get_db base_cells $cell]
set lc [get_db $bc .lib_cells]
if { [get_db $bc .lef_file_name] != "" } {
    set x [expr [get_db $bc .bbox.ur.x] - [get_db $bc .bbox.ll.x]]
    set y [expr [get_db $bc .bbox.ur.y] - [get_db $bc .bbox.ll.y]]
    puts "-I- Cell: $cell. Using lef x and y: $x $y VS $myx $myy"
    if { $x != $myx || $y != $myy } { exit }
    
} else {
    puts "-I- Cell: $cell. Using my x and y: $myx $myy"
    set x $myx 
    set y $myy
}
if { $lc == "" } { puts "-I- Cell: Creating BBOX"
create_blackbox -cell $cell -size $x $y -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
}


###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Tue Feb  1 09:41:17 IST 2022
#  Design:            grid_ecore_cluster
#  Size:              759.696 1108.80
#  File Name:         scripts_local/create_blackboxes.tcl
#  User:              ory
###############################################################


set cell grid_ecore_cluster
set myx  1193.808
set myy  1108.80
set bc [get_db base_cells $cell]
set lc [get_db $bc .lib_cells]
if { [get_db $bc .lef_file_name] != "" } {
    set x [expr [get_db $bc .bbox.ur.x] - [get_db $bc .bbox.ll.x]]
    set y [expr [get_db $bc .bbox.ur.y] - [get_db $bc .bbox.ll.y]]
    puts "-I- Cell: $cell. Using lef x and y: $x $y VS $myx $myy"
    if { $x != $myx || $y != $myy } { exit }
    
} else {
    puts "-I- Cell: $cell. Using my x and y: $myx $myy"
    set x $myx 
    set y $myy
}
if { $lc == "" } { puts "-I- Cell: Creating BBOX"
create_blackbox -cell $cell -size $x $y -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
}
