
###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Mon Jan 24 14:27:45 IST 2022
#  Design:            cbui_top
#  Size:              786.828 544.32
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell cbui_top -size 786.828 544.32 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Mon Jan 24 14:27:45 IST 2022
#  Design:            nfi_mcu_top
#  Size:              406.98 1088.64
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell nfi_mcu_top -size 406.98 1088.64 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Mon Jan 24 14:27:45 IST 2022
#  Design:            cbue_top
#  Size:              786.828 544.32
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell cbue_top -size 786.828 544.32 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Mon Jan 24 14:27:45 IST 2022
#  Design:            tcu_top
#  Size:              786.828 1088.64
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell tcu_top -size 786.828 1088.64 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Mon Jan 24 14:27:45 IST 2022
#  Design:            w_filler
#  Size:              27.132 7680.960
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell w_filler -size 27.132 7680.960 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18} -pin_layer_top {4 6 8 10 12 14 16 18} -pin_layer_bottom {4 6 8 10 12 14 16 18} \
    -pin_layer_left {5 7 9 11 13 15 17} -pin_layer_right {5 7 9 11 13 15 17}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Mon Jan 24 14:27:45 IST 2022
#  Design:            se_filler
#  Size:              54.264 8779.680
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell se_filler -size 54.264 8779.680 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18} -pin_layer_top {4 6 8 10 12 14 16 18} -pin_layer_bottom {4 6 8 10 12 14 16 18} \
    -pin_layer_left {5 7 9 11 13 15 17} -pin_layer_right {5 7 9 11 13 15 17}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Mon Jan 24 14:27:45 IST 2022
#  Design:            ne_filler
#  Size:              54.264 8779.680
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell ne_filler -size 54.264 8779.680 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18} -pin_layer_top {4 6 8 10 12 14 16 18} -pin_layer_bottom {4 6 8 10 12 14 16 18} \
    -pin_layer_left {5 7 9 11 13 15 17} -pin_layer_right {5 7 9 11 13 15 17}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Mon Jan 24 14:27:45 IST 2022
#  Design:            s_filler
#  Size:              9007.824 20.160
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell s_filler -size 9007.824 20.160 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18} -pin_layer_top {4 6 8 10 12 14 16 18} -pin_layer_bottom {4 6 8 10 12 14 16 18} \
    -pin_layer_left {5 7 9 11 13 15 17} -pin_layer_right {5 7 9 11 13 15 17}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Mon Jan 24 14:27:45 IST 2022
#  Design:            n_filler
#  Size:              9740.388 20.160
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell n_filler -size 9740.388 20.160 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18} -pin_layer_top {4 6 8 10 12 14 16 18} -pin_layer_bottom {4 6 8 10 12 14 16 18} \
    -pin_layer_left {5 7 9 11 13 15 17} -pin_layer_right {5 7 9 11 13 15 17}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Mon Jan 24 14:27:45 IST 2022
#  Design:            icovlb
#  Size:              87.12 218.832
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell icovlb -size 87.12 218.832 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13} -pin_layer_top {4 6 8 10 12} -pin_layer_bottom {4 6 8 10 12} \
    -pin_layer_left {5 7 9 11 13} -pin_layer_right {5 7 9 11 13}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Mon Jan 24 14:27:45 IST 2022
#  Design:            icovlc
#  Size:              87.12 151.632
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell icovlc -size 87.12 151.632 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13} -pin_layer_top {4 6 8 10 12} -pin_layer_bottom {4 6 8 10 12} \
    -pin_layer_left {5 7 9 11 13} -pin_layer_right {5 7 9 11 13}
    

################################################################
##  Generated by:      create_blackbox_file script
##  Generated on:      Mon Jan 24 14:27:45 IST 2022
##  Design:            icovld
##  Size:              225.84 84.432
##  File Name:         scripts_local/create_blackboxes_w_hips.tcl
##  User:              ory
################################################################
#
#
#
#create_blackbox -cell icovld -size 225.84 84.432 -core_spacing 0 0 0 0 \
#    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
#    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13} -pin_layer_top {4 6 8 10 12} -pin_layer_bottom {4 6 8 10 12} \
#    -pin_layer_left {5 7 9 11 13} -pin_layer_right {5 7 9 11 13}
#    
#
################################################################
##  Generated by:      create_blackbox_file script
##  Generated on:      Mon Jan 24 14:27:45 IST 2022
##  Design:            icovle
##  Size:              156.48 84.432
##  File Name:         scripts_local/create_blackboxes_w_hips.tcl
##  User:              ory
################################################################
#
#
#create_blackbox -cell icovle -size 156.48 84.432 -core_spacing 0 0 0 0 \
#    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
#    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13} -pin_layer_top {4 6 8 10 12} -pin_layer_bottom {4 6 8 10 12} \
#    -pin_layer_left {5 7 9 11 13} -pin_layer_right {5 7 9 11 13}
#    



create_blackbox -cell vtmon -size 29.784 19.376 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 } -pin_layer_top {4 6 8} -pin_layer_bottom {4 6 8} \
    -pin_layer_left {5 7 } -pin_layer_right {5 7}
    
create_blackbox -cell icovlh -size 15.504 81.312 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13} -pin_layer_top {4 6 8} -pin_layer_bottom {4 6 8} \
    -pin_layer_left {5 7 } -pin_layer_right {5 7}

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Tue Feb  1 09:37:49 IST 2022
#  Design:            nfi_mcu_top
#  Size:              406.98 1088.64
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell nfi_mcu_top -size 406.98 1088.64 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Tue Feb  1 09:37:49 IST 2022
#  Design:            cbue_top
#  Size:              786.828 544.32
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell cbue_top -size 786.828 544.32 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Tue Feb  1 09:37:49 IST 2022
#  Design:            tcu_top
#  Size:              786.828 1088.64
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell tcu_top -size 786.828 1088.64 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Tue Feb  1 09:37:49 IST 2022
#  Design:            grid_quad_east_filler_row_top
#  Size:              162.792 1088.64
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell grid_quad_east_filler_row_top -size 162.792 1088.64 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Tue Feb  1 09:37:49 IST 2022
#  Design:            grid_quad_west_filler_row_top
#  Size:              54.264 1088.64
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell grid_quad_west_filler_row_top -size 54.264 1088.64 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Tue Feb  1 09:37:49 IST 2022
#  Design:            grid_quad_south_filler_row_top
#  Size:              1193.808 20.16
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell grid_quad_south_filler_row_top -size 1193.808 20.16 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
    

###############################################################
#  Generated by:      create_blackbox_file script
#  Generated on:      Tue Feb  1 09:37:49 IST 2022
#  Design:            grid_quad_north_filler_row_top
#  Size:              1193.808 20.16
#  File Name:         scripts_local/create_blackboxes_w_hips.tcl
#  User:              ory
###############################################################



create_blackbox -cell grid_quad_north_filler_row_top -size 1193.808 20.16 -core_spacing 0 0 0 0 \
    -min_pitch_left 2 -min_pitch_right 2 -min_pitch_top 2 -min_pitch_bottom 2 \
    -reserved_layer {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16} -pin_layer_top {4 6 8 10 12 14 16} -pin_layer_bottom {4 6 8 10 12 14 16} \
    -pin_layer_left {5 7 9 11 13 15} -pin_layer_right {5 7 9 11 13 15}
    
